# Generated by Django 5.0.3 on 2024-04-06 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerVerify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('postalcode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=110, null=True)),
                ('pictures', models.FileField(blank=True, null=True, upload_to='producer_pictures')),
                ('document', models.FileField(blank=True, null=True, upload_to='producer_documents')),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('postalcode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=110, null=True)),
                ('pictures', models.FileField(blank=True, null=True, upload_to='producer_pictures')),
                ('document', models.FileField(blank=True, null=True, upload_to='producer_documents')),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
