# Generated by Django 5.0.2 on 2024-03-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='aadharNumber',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='created',
        ),
        migrations.AddField(
            model_name='producer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='postalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='firstName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producer',
            name='lastName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
