# Generated by Django 5.0.3 on 2024-03-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_producer_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='producer_documents'),
        ),
    ]
