# Generated by Django 5.0.3 on 2024-03-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='producer_pictures'),
        ),
    ]
