# Generated by Django 5.0.3 on 2024-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='pictures',
            field=models.FileField(blank=True, null=True, upload_to='producer_pictures'),
        ),
    ]
