# Generated by Django 5.0.2 on 2024-03-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
