# Generated by Django 5.0.3 on 2024-03-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0008_producer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produce',
            options={'ordering': ['produceName']},
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='available_quantity',
            new_name='availableQuantity',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='name',
            new_name='produceName',
        ),
    ]
