# Generated by Django 5.0.3 on 2024-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0010_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerVerify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('postalcode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=110, null=True)),
                ('pictures', models.FileField(blank=True, null=True, upload_to='producer_pictures')),
                ('document', models.FileField(blank=True, null=True, upload_to='producer_documents')),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
