# Generated by Django 5.0.3 on 2024-03-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0011_producer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
