# Generated by Django 5.0.3 on 2024-03-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0012_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produceName', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grain', 'Grain'), ('Herb', 'Herb'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availableQuantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='producer.producer')),
            ],
            options={
                'ordering': ['produceName'],
            },
        ),
    ]
